print ("what is your name?")
name = input()
print ("what is your email?")
email = input()
print ("what is your contact?")
contact = input()
print ("what is your access level?")
access = input()
print ("|---------------------------------------|")
print ("| Apex Entertainment Pass               |")
print ("|---------------------------------------|")
print ("| ATTENDEE : " + name.ljust(27) + "|")
print ("| ORG : " + email.ljust(32) + "|")
print ("| CONTACT : " + email.ljust(28) + "|")
print ("| ACCESS : " + access.ljust(29) + "|")
print ("| ISSURER : " + "BCH Software Terminal System" + "|")