print ("what is your name?")
name = input()
print (name)
print ("what is your email?")
email = input()
print (email)
print ("|-------------------------|")
print ("| Apex Entertainment Pass |")
print ("|-------------------------|")
print ("| ATTENDEE : " + name.ljust(13) + "|")
print ("| ORG : " + email.ljust(18) + "|")